In [ ]:
"""
WHY NUMPY?

Tensors Vectorization Tensor Operations Other Libaries Efficiency

"""



# Objects in Python

type()Function

In [1]:
a = [1,2,3]
b = {'a':1,'b':2,'c':3}
c = (1,2,3)

print('list :',type(a))
"""
순서가 있는 수정가능한 객체의 집합입니다.
수정, 삭제, 추가가 가능합니다.
list 는 [] 대괄호로 작성되어지며, 내부 원소는 ,로 구분됩니다.
REPL에서 확인하겠습니다. 일반 list 입니다.
"""
print('list :',type(b))
"""
딕셔너리 타입은 immutable한 키(key)와 mutable한 값(value)으로 맵핑되어 있는 순서가 없는 집합입니다.
REPL에서 확인합니다.
일반적인 딕셔너리 타입의 모습입니다. 중괄호로 되어 있고 키와 값이 있습니다.
"""

print('list :',type(c))
"""
tuple(튜플)은 불변한 순서가 있는 객체의 집합입니다.
list형과 비슷하지만 한 번 생성되면 값을 변경할 수 없습니다.
REPL에서 확인해봅니다.
list와 마찬가지로 다양한 타입이 함께 포함될 수 있습니다.
"""



<class 'list'>
<class 'dict'>
<class 'tuple'>


## Object = Data + Methods

In [2]:
a = [1,2,3] # instantiate a list
a.append(4) # use "append" method to append 3 to the list
print(a)

[1, 2, 3, 4]


## dir()Function

In [3]:
a = [1,2,3]
for attr in dir(a):
    print(attr)

__add__
__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__getstate__
__gt__
__hash__
__iadd__
__imul__
__init__
__init_subclass__
__iter__
__le__
__len__
__lt__
__mul__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__reversed__
__rmul__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
append
clear
copy
count
extend
index
insert
pop
remove
reverse
sort


In [4]:
a = {'a':0, 'b':1, 'c':2}
for attr in dir(a):
    print(attr)

__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__getstate__
__gt__
__hash__
__init__
__init_subclass__
__ior__
__iter__
__le__
__len__
__lt__
__ne__
__new__
__or__
__reduce__
__reduce_ex__
__repr__
__reversed__
__ror__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
clear
copy
fromkeys
get
items
keys
pop
popitem
setdefault
update
values


## Special Method Examples

실제 컴터는 이렇게 이해합니다!

In [5]:
a, b = 4, 2

print(a - b, a.__sub__(b))
print(a * b, a.__mul__(b))
print(a ** b, a.__pow__(b))
print(a / b, a.__truediv__(b))
print(a - b, a.__sub__(b))
print(a // b, a.__floordiv__(b))
print(a % b, a.__mod__(b))

2 2
8 8
16 16
2.0 2.0
2 2
2 2
0 0


In [9]:
a = [1,2,3]
for attr1 in dir(a):
    print('attr list',attr1)
    
a = {'a':0,'b':1,'c':2}
for attr2 in dir(a):
    print('attr dictionary',attr2)

attr list __add__
attr list __class__
attr list __class_getitem__
attr list __contains__
attr list __delattr__
attr list __delitem__
attr list __dir__
attr list __doc__
attr list __eq__
attr list __format__
attr list __ge__
attr list __getattribute__
attr list __getitem__
attr list __getstate__
attr list __gt__
attr list __hash__
attr list __iadd__
attr list __imul__
attr list __init__
attr list __init_subclass__
attr list __iter__
attr list __le__
attr list __len__
attr list __lt__
attr list __mul__
attr list __ne__
attr list __new__
attr list __reduce__
attr list __reduce_ex__
attr list __repr__
attr list __reversed__
attr list __rmul__
attr list __setattr__
attr list __setitem__
attr list __sizeof__
attr list __str__
attr list __subclasshook__
attr list append
attr list clear
attr list copy
attr list count
attr list extend
attr list index
attr list insert
attr list pop
attr list remove
attr list reverse
attr list sort
attr dictionary __class__
attr dictionary __class_getitem__
attr 

## ndarry Objects

In [10]:
import numpy as np

a = np.array([1,2,3])
print(type(a)) 

<class 'numpy.ndarray'>


## ndarry Objects

In [11]:
import numpy as np

a = np.array([1,2,3])
for attr in dir(a):
    print('ndarray:',attr)

ndarray: T
ndarray: __abs__
ndarray: __add__
ndarray: __and__
ndarray: __array__
ndarray: __array_finalize__
ndarray: __array_function__
ndarray: __array_interface__
ndarray: __array_prepare__
ndarray: __array_priority__
ndarray: __array_struct__
ndarray: __array_ufunc__
ndarray: __array_wrap__
ndarray: __bool__
ndarray: __class__
ndarray: __class_getitem__
ndarray: __complex__
ndarray: __contains__
ndarray: __copy__
ndarray: __deepcopy__
ndarray: __delattr__
ndarray: __delitem__
ndarray: __dir__
ndarray: __divmod__
ndarray: __dlpack__
ndarray: __dlpack_device__
ndarray: __doc__
ndarray: __eq__
ndarray: __float__
ndarray: __floordiv__
ndarray: __format__
ndarray: __ge__
ndarray: __getattribute__
ndarray: __getitem__
ndarray: __getstate__
ndarray: __gt__
ndarray: __hash__
ndarray: __iadd__
ndarray: __iand__
ndarray: __ifloordiv__
ndarray: __ilshift__
ndarray: __imatmul__
ndarray: __imod__
ndarray: __imul__
ndarray: __index__
ndarray: __init__
ndarray: __init_subclass__
ndarray: __int__


## Element-wise Oprations of ndarrays

In [12]:
u = [1,2,3] 
v = [4,5,6]

w = u + v 
print(w)

[1, 2, 3, 4, 5, 6]


In [15]:
u = [1, 2, 3]
v = [4, 5, 6]

w = u + v
print('with narrays',w)

# ndarry가 아닌경우는 힘들게 직접 원소에 반복문으로 접근해야함!
w = [0]*len(u)
for data_idx in range(len(u)):
    w[data_idx] = u[data_idx] + v[data_idx]
    print('with Python Lists',w)

[1, 2, 3, 4, 5, 6]
not ndarray [5, 0, 0]
not ndarray [5, 7, 0]
not ndarray [5, 7, 9]


# Element-wise Operations of ndarrays

In [22]:
M =[[1,2,3],[4,5,6],[7,8,9]]
N = [[11,12,13],[14,15,16],[17,18,19]]

n_row, n_col = len(M), len(M[0])

p = [[0]*n_col for _ in range(n_col)]
for row_idx in range(n_row):
    for col_idx in range(n_col):
        p[row_idx][col_idx] = M[row_idx][col_idx] + \
            N[row_idx][col_idx]

for P_row in p:
    
    
    import numpy as np
    
    M = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
    
    N = np.array([[11, 12, 13],
                  [14, 15, 16],
                  [17, 18, 19]])
    
    print("Python array",P_row)
    print('ndarray',M + N)
    

Python array [12, 14, 16]
ndarray [[12 14 16]
 [18 20 22]
 [24 26 28]]
Python array [18, 20, 22]
ndarray [[12 14 16]
 [18 20 22]
 [24 26 28]]
Python array [24, 26, 28]
ndarray [[12 14 16]
 [18 20 22]
 [24 26 28]]
