np.reshape and ndarray.reshape<br/>

### numpy.reshape(a, newshape, order = 'C')




In [2]:
import numpy as np

a = np.arange(6)
b = np.reshape(a, (2,3))

print("original ndarray: \n", a)
print("reshaped ndarray: \n", b)

original ndarray: 
 [0 1 2 3 4 5]
reshaped ndarray: 
 [[0 1 2]
 [3 4 5]]


## Changing ndarrays' shapes

np.reshape and ndarray.reshape

In [3]:
import numpy as np

a = np.arange(24)
b = np.reshape(a,(2 ,3 ,4))

print("original ndarray: \n",a)
print("reshaped ndarray: \n",b)

original ndarray: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
reshaped ndarray: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## -1 in np.reshape

In [8]:
import numpy as np

a = np.arange(12)
print('a is original\n',a)
print('a is original.shape\n',a.shape)
b = a.reshape((2, -1))
c = a.reshape((3, -1))
d = a.reshape((4, -1))
e = a.reshape((6, -1))

# -1 을 하게 되면 row의 수 만큼, np.array를 잘라서 저장 
print('a reshape\n',b.shape, c.shape, d.shape, e.shape)


a is original
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
a is original.shape
 (12,)
a reshape
 (2, 6) (3, 4) (4, 3) (6, 2)


## -1 in np.reshape

In [9]:
import numpy as np

a = np.arange(12)

b = a.reshape((-1, 2))
c = a.reshape((-1, 3))
d = a.reshape((-1, 4))
e = a.reshape((-1, 6))

print(b.shape, c.shape,
      d.shape, e.shape)

(6, 2) (4, 3) (3, 4) (2, 6)


## - Changing ndarray's shape

-1 in np.reshape

In [10]:
a = np.random.randint(0, 10, size=(2,3))

print(a)

# 앞에서 배운 reshape의 개념을 row와 columns에 적용시켜서,각 elemenat의 수를 -1 로 가져와서
# reshape
row_vector = a.reshape(1,-1)
col_vector = a.reshape(-1,1)

print(row_vector.shape, col_vector.shape)

[[0 5 3]
 [6 0 5]]
(1, 6) (6, 1)


****매우 중요 자주 쓰임*********<br>

## np.flatten

ndarray.flatten(order='C')

In [16]:
import numpy as np

M = np.arange(9)
N = M.reshape((3,3))
O = N.flatten()

print("numpy array로 생성",M, '\n')
print("numpy array로 생성",M.shape, '\n')
print("M을 (3,3) 형태로 변환",N)
print("\nM을 (3,3) 형태로 변환",N.shape, '\n')
print("변환한 거 펼쳐, flatten은 평평하니꼐 ",O, '\n')
print("변환한 거 펼쳐, flatten은 평평하니꼐 ",O.shape, '\n')

numpy array로 생성 [0 1 2 3 4 5 6 7 8] 

numpy array로 생성 (9,) 

M을 (3,3) 형태로 변환 [[0 1 2]
 [3 4 5]
 [6 7 8]]

M을 (3,3) 형태로 변환 (3, 3) 

변환한 거 펼쳐, flatten은 평평하니꼐  [0 1 2 3 4 5 6 7 8] 

변환한 거 펼쳐, flatten은 평평하니꼐  (9,) 


In [18]:
import numpy as np

M = np.arange(27)
n = M.reshape(3,3,3)
O = N.flatten()

print("M",M, '\n')
print("M",M, '\n')
print("N",N.shape, '\n')
print("N",N, '\n')
print("O",O, '\n')
print("O",O.shape, '\n')

M [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 

M [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 

N (3, 3) 

N [[0 1 2]
 [3 4 5]
 [6 7 8]] 

O [0 1 2 3 4 5 6 7 8] 

O (9,) 


## Lecture.6 Element-wise Operations and Broadcasting

# Elenent - wise Operations of ndarrys

# Vector - vector Case

In [20]:
import numpy as np

# -5 로 shape을 맞춰주면, BroadCast 기능을 통해서 자동으로 shape이 정해져서 결과값을 출력한다. 
a = np.random.randint(-5,5, (5,))
b = np.random.randint(-5,5, (5,))

print("a:",a)
print("b:",b, '\n')

print("a + b:",a + b)

a: [-5 -2  3 -1 -3]
b: [-1 -2  0 -1 -4] 

a + b: [-6 -4  3 -2 -7]


In [21]:
import numpy as np

a = np.random.randint(1,5,(5,))
b = np.random.randint(1,5,(5,))

print("a ",a)
print("b ",b, '\n')

print("a + b: ", a + b)
print("a - b: ", a - b)
print("a * b: ", a * b)
print("a / b: ", a / b)
print("a // b: ", a // b)
print("a % b: ", a % b)
print("a ** b: ", a ** b)

a  [3 1 3 2 1]
b  [2 2 2 4 2] 

a + b:  [5 3 5 6 3]
a - b:  [ 1 -1  1 -2 -1]
a * b:  [6 2 6 8 2]
a / b:  [1.5 0.5 1.5 0.5 0.5]
a // b:  [1 0 1 0 0]
a % b:  [1 1 1 2 1]
a ** b:  [ 9  1  9 16  1]
