## Vector-vector Case
### Element-wise Operations of ndarrays

In [1]:
# 52
import numpy as np

# 1부터 5까지 정수형 난수 생성, 이떄 생성되는 array a,b는 np.array
# 따리서 Elemnet-Wise Operations 가능!
a = np.random.randint(1, 5, (5,))
b = np.random.randint(1, 5, (5,))

print("a ",a)
print("b ",b,'\n')

print(" a + b ", a + b)
print(" a - b ", a - b)
print(" a * b ", a * b)
# / 나누기
print(" a / b ", a / b)
# 몫
print(" a // b ", a // b)
# 나머지
print(" a % b ", a % b)
# 제곱
print(" a ** b ", a ** b)


a  [1 3 1 3 1]
b  [2 3 4 4 1] 

 a + b  [3 6 5 7 2]
 a - b  [-1  0 -3 -1  0]
 a * b  [ 2  9  4 12  1]
 a / b  [0.5  1.   0.25 0.75 1.  ]
 a // b  [0 1 0 0 1]
 a % b  [1 0 1 3 0]
 a ** b  [ 1 27  1 81  1]


In [2]:
#53

import numpy as np

a = np.random.randint(1, 5, (5,))
b = np.random.randint(1, 5, (5,))

print("a: ",a)
print("b: ",b, '\n')

print("a > b", a > b)
print("a >= b", a > b)
print("a < b", a > b)
print("a <= b", a > b)
print("a <= b", a > b)
# 같다 == 
print("a == b", a > b)
# 다르다
print("a != b", a > b)

a:  [4 3 1 3 2]
b:  [2 2 3 1 2] 

a > b [ True  True False  True False]
a >= b [ True  True False  True False]
a < b [ True  True False  True False]
a <= b [ True  True False  True False]
a <= b [ True  True False  True False]
a == b [ True  True False  True False]
a != b [ True  True False  True False]


In [4]:
# 54
import numpy as np

a = np.random.randint(1, 5, (5,))
b = np.random.randint(1, 5, (5,))

print("a ",a)
print("b ",b,'\n')
# __init__ 의 형태는 스페셜 메서드
print(" a + b", a.__add__(b))
print(" a - b", a.__sub__(b))
print(" a * b", a.__mul__(b))
print(" a / b", a.__truediv__(b))
print(" a // b", a.__floordiv__(b))
print(" a % b", a.__mod__(b))
print(" a ** b", a.__pow__(b))




a  [4 2 2 1 1]
b  [1 4 3 1 4] 

 a + b [5 6 5 2 5]
 a - b [ 3 -2 -1  0 -3]
 a * b [4 8 6 1 4]
 a / b [4.         0.5        0.66666667 1.         0.25      ]
 a // b [4 0 0 1 0]
 a % b [0 2 2 0 1]
 a ** b [ 4 16  8  1  1]


# Matrix- mattrix 

matrix의 연산에도 element_wise 적용가능


In [5]:
import numpy as np

M = np.random.randint(1, 5, (2, 3))
N = np.random.randint(1, 5, (2, 3))

print("M: \n",M)
print("M: \n",N)

print("M + N: \n",M + N)
print("M - N: \n",M - N)

print("M > N", M > N)
print("M >= N", M >= N)

M: 
 [[2 1 4]
 [4 4 4]]
M: 
 [[4 4 3]
 [4 4 3]]
M + N: 
 [[6 5 7]
 [8 8 7]]
M - N: 
 [[-2 -3  1]
 [ 0  0  1]]
M > N [[False False  True]
 [False False  True]]
M >= N [[False False  True]
 [ True  True  True]]


## Broadcasting in Numpy

1번쨰, (3,3) + (3,1) => (3,3) + (3,3) = (3,3)
비어있다면, 알아서 채워준다.

In [6]:
# p60
# When ndims are Equal(Matricse)

import numpy as np
# 3x3 메트릭스 생성
A = np.arange(9).reshape(3,3)
# 3x1 matrix 생성
# A와 비교해서 column의 방향만큼 원소 생성
"""
0   0  0
10  10 10
20  20 20 
"""
B = 10*np.arange(3).reshape((3,-1))
# 더하게 되면 자동으로 채워준다.
# B의 원소는 A의 shape만큼 생성됨 
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(B.ndim, B.shape, B))
print("C: {}/{}\n{}".format(C.ndim, C.shape, C))


A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B: 2/(3, 1)
[[ 0]
 [10]
 [20]]
C: 2/(3, 3)
[[ 0  1  2]
 [13 14 15]
 [26 27 28]]


## 3차원에서의 이해

## Rank3 
## 3-tensor :(o, n, m)

## case1

(2,3,3) + (1,3,3)

=> Broadcasting 

(2,3,3) + (2,3,3)

= (2,3,3)

In [7]:
# When ndims Are Equal(3rd Order Tensors)
# P 64

import numpy as np

A = np.arange(18).reshape((2,3,3))
B = 10*np.arange(9).reshape(1,3,3)
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(A.ndim, B.shape, B))

print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(1, 3, 3)
[[[ 0 10 20]
  [30 40 50]
  [60 70 80]]]
A + B: 3/(2, 3, 3)
[[[ 0 11 22]
  [33 44 55]
  [66 77 88]]

 [[ 9 20 31]
  [42 53 64]
  [75 86 97]]]


## Case2

(2,3,3) + (2,1,3)

=> Broadcasting 

(2,3,3) + (2,3,3)

= (2,3,3)

In [8]:
# when ndims Are Equal(3rd Order Tensors)

import numpy as np

# (2,3,3)
A = np.arange(18).reshape((2, 3, 3))
# (2,1,3)
B = 10*np.arange(6).reshape((2, 1, 3))
"""
b 0 10 20
  0 10 20
  0 10 20 

  30 40 50
  30 40 50
  30 40 50 
"""
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(A.ndim, B.shape, B))

print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(2, 1, 3)
[[[ 0 10 20]]

 [[30 40 50]]]
A + B: 3/(2, 3, 3)
[[[ 0 11 22]
  [ 3 14 25]
  [ 6 17 28]]

 [[39 50 61]
  [42 53 64]
  [45 56 67]]]


In [9]:
import numpy as np

A = np.arange(18).reshape((2,3,3))
B = 10*np.arange(6).reshape((2,3,1))

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(A.ndim, B.shape, B))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
B: 3/(2, 3, 1)
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]]
A + B: 3/(2, 3, 3)
[[[ 0 11 22]
  [ 3 14 25]
  [ 6 17 28]]

 [[39 50 61]
  [42 53 64]
  [45 56 67]]]


In [10]:
#70

import numpy as np

A = np.arange(6).reshape((2, 1, 3))
B = np.arange(6).reshape((2, 3, 1))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(A.ndim, B.shape, B))

print("A+B".format(A.ndim, C.shape, C))





A: 3/(2, 1, 3)
[[[0 1 2]]

 [[3 4 5]]]
B: 3/(2, 3, 1)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
A+B


In [11]:
# 71
# when ndims are Not Equal

import numpy as np

a = np.array(3)
u = np.arange(5)

print("Shapes: {}/{}".format(a.shape, u.shape))
print("a : ",a)
print("u ",u,'\n')

print("a*u", a*u)

Shapes: ()/(5,)
a :  3
u  [0 1 2 3 4] 

a*u [ 0  3  6  9 12]


In [13]:
import numpy as np

a = np.array(3)
u = np.arange(1,5)

shapes ="shapes: {}/{}"
print(shapes.format(a.shape, u.shape))

print("a",a)
print("u",u, '\n')

print("a + u",a + u)
print("a - u",a - u)
print("a * u",a * u)
print("a / u",a / u)
print("a // u",a // u)

print("a % u",a % u)
print("a ** u",a ** u,'\n')


print("a > u",a > u)
print("a >= u",a >= u)
print("a < u",a < u)
print("a <= u",a <= u)
print("a == u",a == u)
print("a != u",a != u)


shapes: ()/(4,)
a 3
u [1 2 3 4] 

a + u [4 5 6 7]
a - u [ 2  1  0 -1]
a * u [ 3  6  9 12]
a / u [3.   1.5  1.   0.75]
a // u [3 1 1 0]
a % u [0 1 0 3]
a ** u [ 3  9 27 81] 

a > u [ True  True False False]
a >= u [ True  True  True False]
a < u [False False False  True]
a <= u [False False  True  True]
a == u [False False  True False]
a != u [ True  True False  True]


## (2,) + (3,2) => (3,2) + (3,2) = (3,2)

부족한 (2,)을 뒤에 있는 (3,2) 기준으로 원소의 갯수 맞춰주기
(2,3) (3,2) 처럼 row와 column이 일치하면 가능해진다.

In [14]:
# when nidms Are Not Equal

import numpy as np

A = np.array([10,20])
B = np.arange(6).reshape((3,2))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 1/(2,)
[10 20]
B: 1/(3, 2)
[[10 21]
 [12 23]
 [14 25]]


In [15]:
import numpy as np

A = np.arange(2*3*4).reshape((2,3,4))
B = 10*np.arange(3*4).reshape((3,4))
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(A.ndim, C.shape, C))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: 3/(2, 3, 4)
[[[  0  11  22  33]
  [ 44  55  66  77]
  [ 88  99 110 121]]

 [[ 12  23  34  45]
  [ 56  67  78  89]
  [100 111 122 133]]]
A + B: 3/(2, 3, 4)
[[[  0  11  22  33]
  [ 44  55  66  77]
  [ 88  99 110 121]]

 [[ 12  23  34  45]
  [ 56  67  78  89]
  [100 111 122 133]]]


(2,3,4) + (4, )
=> Broadcasting (2,3,4) + (2,3,4)
= (2,3,4)

In [16]:
# 78
# when ndims ara Not Equal

import numpy as np

A = np.arange(2*3*4).reshape((2,3,4))
B = 10*np.arange(4)
C = A + B

print("A: {}/{}\n{}".format(A.ndim, A.shape, A))
print("B: {}/{}\n{}".format(A.ndim, C.shape, C))
print("A + B: {}/{}\n{}".format(A.ndim, C.shape, C))

A: 3/(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
B: 3/(2, 3, 4)
[[[ 0 11 22 33]
  [ 4 15 26 37]
  [ 8 19 30 41]]

 [[12 23 34 45]
  [16 27 38 49]
  [20 31 42 53]]]
A + B: 3/(2, 3, 4)
[[[ 0 11 22 33]
  [ 4 15 26 37]
  [ 8 19 30 41]]

 [[12 23 34 45]
  [16 27 38 49]
  [20 31 42 53]]]


차원이 갖지 않을떄는 어떻게???

In [17]:
# Indexing and Slicing Vector ndarrays

import numpy as np

a = np.arange(10)
print(f"ndarray: \n{a}\n")

print(f"a[0]:",a[0])
print(f"a[2]:",a[2])

print(f"a[-1]:",a[-1]) # the last elemnet
print(f"a[-2]:",a[-2]) # the 2nd last element

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[0]: 0
a[2]: 2
a[-1]: 9
a[-2]: 8


In [18]:
import numpy as np

a = np.arange(10)
print(f"ndarray: \n{a}\n")

print("a[0:3]",a[0:3])

print("a[3:7]",a[3:7])

print("a[5:-1]",a[5:-1])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[0:3] [0 1 2]
a[3:7] [3 4 5 6]
a[5:-1] [5 6 7 8]


In [19]:
#82
# Indexing and Slicing Vector ndarrays

import numpy as np

a = np.arange(10)

print(f"ndarray: \n{a}\n")

print("a[2:]",a[2:])

print("a[:-2]",a[-2:])

print("a[:5]",a[:5])

print("a[:-3]",a[:-3])

print("a[:]",a[:])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:] [2 3 4 5 6 7 8 9]
a[:-2] [8 9]
a[:5] [0 1 2 3 4]
a[:-3] [0 1 2 3 4 5 6]
a[:] [0 1 2 3 4 5 6 7 8 9]


## [strat : end : step]

In [20]:
# indexing and Slicing Vevtor ndarrays

import numpy as np

a = np.arange(10)

print(f"ndarray: \n{a}\n")

print("a[2:7:2]",a[2:7:2])

print("a[::3] :", a[::3])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

a[2:7:2] [2 4 6]
a[::3] : [0 3 6 9]


In [21]:
# Indexing and Slicing Vector ndarrays

import numpy as np

a = np.arange(10)

print(f"ndarray:\n{a}\n")

print("a[7:2:-1] :", a[::-1])

print("a[8:3:-2] :", a[8:3:-2])

print("a[::-3] :",a[::-3])

ndarray:
[0 1 2 3 4 5 6 7 8 9]

a[7:2:-1] : [9 8 7 6 5 4 3 2 1 0]
a[8:3:-2] : [8 6 4]
a[::-3] : [9 6 3 0]


In [22]:
# Indexing and Slicing Matrix ndarrays
a1 = [[0,1,2],[3,4,5],[6,7,8]] 
print(a1[0])
print(a1[1])
print(a1[2])

a2 = [[0,1,2],[3,4,5],[6,7,8]]
print(a2[0])
print(a2[1])
print(a2[2])

[0, 1, 2]
[3, 4, 5]
[6, 7, 8]
[0, 1, 2]
[3, 4, 5]
[6, 7, 8]


In [23]:
# Indexing and SLicing Matrix ndarrays

import numpy as np

a = np.arange(12).reshape((3,4))

print(f"ndarray: \n{a}\n")

print("a[0] :", a[0])

print("a[1] :", a[1])

print("a[2] :", a[2])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0] : [0 1 2 3]
a[1] : [4 5 6 7]
a[2] : [ 8  9 10 11]


  inner dim ->
o [ [0 1 2 3], 
u   [4 5 6 7],
t   [8 9 10 11]]
e
r
d
i
m
|
v

In [24]:
import numpy as np

a = np.arange(9).reshape((3,3))
print(f"ndarray: \n{a}\n")

print(a[0,0], a[0,1], a[0,2])
print(a[1,0], a[1,1], a[1,2])
print(a[2,0], a[2,1], a[2,2])


ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2
3 4 5
6 7 8


In [26]:
import numpy as np

a = np.arange(9).reshape((3,3))

print(f"narray: \n{a}\n")

print(a[0,0], a[0,1], a[0,2])
print(a[1,0], a[1,1], a[1,2])
print(a[2,0], a[2,1], a[2,2])



narray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

0 1 2
3 4 5
6 7 8


In [27]:
import numpy as np

a = np.arange(9).reshape((3,3))
print(f"ndarray: \n{a}\n")

ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
import numpy as np

a = np.arange(12).reshape((3,4))

print(f"a[0, 1:] : ",a[0, 1:])

print(f"a[1, :3] : ",a[1, :3])

print(f"a[2, 1:3] : ",a[2, 1:3])

a[0, 1:] :  [1 2 3]
a[1, :3] :  [4 5 6]
a[2, 1:3] :  [ 9 10]


In [29]:
import numpy as np

a = np.arange(12).reshape((4,3))

print(f"a[0, 1:] : ",a[1:, 0])

print(f"a[1, :3] : ",a[:3, 1])

print(f"a[2, 1:3] : ",a[1:3, 2])

a[0, 1:] :  [3 6 9]
a[1, :3] :  [1 4 7]
a[2, 1:3] :  [5 8]


In [30]:
import numpy as np

a = np.arange(3*3*3).reshape((3,3,3))
print(f"ndarray: \n{a}\n")

ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [31]:
print("a[:, :2, :] \n", a[:, :2, :])

a[:, :2, :] 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 9 10 11]
  [12 13 14]]

 [[18 19 20]
  [21 22 23]]]


In [33]:
import numpy as np

a = np.arange(3*3*3).reshape((3, 3, 3))
print(f"narray: \n{a}\n")

narray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [34]:
print("a[:,:, 0] : \n",a[:, :, 0])

a[:,:, 0] : 
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
